Hangman\Entity\Hangman:
  type: entity
  repositoryClass: TwitterHangman\ReadModel\Repository\ORM\HangmanRepository
  table: hangman
  schema: minigame
  id:
    id:
      type: guid
      generator:
        strategy: NONE
  fields:
    word:
      column: word
      type: string
      length: 45
      nullable: false
    gameOrder:
      column: game_order
      type: json_array
      nullable: false
  manyToOne:
    currentPlayer:
      targetEntity: HangmanPlayer
      joinColumn:
        name: current_player_id
        referencedColumnName: id
  manyToMany:
    players:
      targetEntity: HangmanPlayer
      joinTable:
        name: minigame.hangman_has_player
        joinColumns:
          hangman_id:
            referencedColumnName: id
        inverseJoinColumns:
          player_id:
            referencedColumnName: id