Hangman\Entity\HangmanPlayer:
  type: entity
  repositoryClass: Hangman\Repository\HangmanPlayerRepository
  table: player
  schema: minigame
  fields:
    name:
      column: name
      type: string
      length: 45
      unique: true
      nullable: false
    lives:
      column: lives
      type: integer
      nullable: false
    playedLetters:
      column: letters_played
      type: json_array
      nullable: false
  manyToOne:
    user:
      targetEntity: TwitterHangman\Entity\TwitterApplicationUser
      joinColumn:
        name: user_id
        referencedColumnName: id
    game:
      targetEntity: Hangman\Entity\Hangman
      inversedBy: players
      joinColumn:
        name: game_id
        referencedColumnName: id
  embedded:
    id:
      class: MiniGame\Entity\PlayerId
      columnPrefix: false